### ISSUE TITLE
Vault

### ISSUE THREAD

**Issue by NavidK0** [slipswhitley/SketchMap#4]
Is there a reason for Vault being required? You really don't need it if you're just checking permissions. Bukkit with hasPermission() will handle perms just fine. In fact, Vault doesn't do anything special when checking perms, Vault itself just uses hasPermission().

Removing Vault would remove a dependency as well.

**Comment by cody-rees** [comment]
Vault is a Permission API that provides a huge list of compatability with a large range of Permissions Plugins including my own plugin PermissionsGS, Not just BukkitPerms. Personally I feel that BukkitPermissions lacks as a Permission provider and is completely unusable for those who run on larger servers, so I will not be removing this feature.

**Comment by NavidK0** [comment]
Fair enough, I was just wondering if you didn't know that Vault is often used for permissions when it doesn't need to be. It's a common mistake.
